name: 'RCE Kunscollecties ETL: harvest & push' 

env:
  BASE_URI: 'https://linkeddata.cultureelerfgoed.nl/'
  ARTIFACT_PATH: 'artifact.tar.gz'
  GRAPH_ID: 'kunstcollecties-latest-graph'
  DATASET_NAME: 'Kunstcollecties-Harvest'

on:
  workflow_dispatch:
    inputs:
      modification:
        description: 'Harvested records must have been modified on or after supplied ISO-8601 date.'
        required: false
        type: string
      push-strategy:
        description: 'How should data be pushed to graph? Select overwrite to replace graph, and merge to combine with current graph.'
        type: choice
        options: 
          - overwrite
          - merge
        required: true
        default: overwrite
    
jobs:
  harvest-and-transform:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        wget 'https://linkeddata.cultureelerfgoed.nl/thesauri/cht/download.trig.gz?graph=https%3A%2F%2Fdata.cultureelerfgoed.nl%2Fterm%2Fid%2Fcht%2Fthesaurus' -O 'cht.trig.gz'
        gunzip cht.trig.gz 
    - name: Harvest and transform 
      run: |
        python src/workflow.py --out 'kc-pt-1.jsonld' -s 0 -e 10000
        python src/workflow.py --out 'kc-pt-2.jsonld' -s 10000 -e 20000
        python src/workflow.py --out 'kc-pt-3.jsonld' -s 20000 -e 30000
        python src/workflow.py --out 'kc-pt-4.jsonld' -s 30000 -e 40000
        python src/workflow.py --out 'kc-pt-5.jsonld' -s 40000 -e 50000
        python src/workflow.py --out 'kc-pt-6.jsonld' -s 50000 -e 60000
        python src/workflow.py --out 'kc-pt-7.jsonld' -s 60000 -e 70000
        python src/workflow.py --out 'kc-pt-8.jsonld' -s 70000 -e 80000
        python src/workflow.py --out 'kc-pt-9.jsonld' -s 80000 -e 90000
        python src/workflow.py --out 'kc-pt-10.jsonld' -s 90000 -e 100000
        python src/workflow.py --out 'kc-pt-11.jsonld' -s 100000 -e 110000
        python src/workflow.py --out 'kc-pt-12.jsonld' -s 110000 -e 120000
        python src/workflow.py --out 'kc-pt-13.jsonld' -s 120000 -e 130000
        python src/workflow.py --out 'kc-pt-14.jsonld' -s 130000 -e 140000
        python src/workflow.py --out 'kc-pt-15.jsonld' -s 140000 -e 150000
        tar cvf - *.jsonld | gzip -9 - > ${{ env.ARTIFACT_PATH }}
      env:
        MODIFIED_ON_OR_AFTER: ${{ inputs.modification }}
    - name: Upload data artifact
      uses: actions/upload-artifact@v7
      with:
        name: data-artifact
        path: ${{ env.ARTIFACT_PATH }}
        overwrite: true

  push-to-triply:
    runs-on: ubuntu-latest
    needs: harvest-and-transform
    steps:
    - name: Download data artifact
      uses: actions/download-artifact@v8
      with:
          name: data-artifact
    - name: Install dependencies
      run: |
        wget 'https://static.triply.cc/cli/triplydb-linux'
        chmod +x triplydb-linux
        tar -xzvf ${{ env.ARTIFACT_PATH }}
    - name: Push changes to TriplyDB API via CLI
      run: |
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-1.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-2.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-3.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-4.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-5.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-6.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-7.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-8.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-9.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-10.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-11.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-12.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-13.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-14.jsonld
        ./triplydb-linux import-from-file --dataset "${{ env.DATASET_NAME }}" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/${{ env.DATASET_NAME }}/graphs/${{ env.GRAPH_ID }}" --mode "${{ inputs.push-strategy }}" kc-pt-15.jsonld
    - name: Print triply error response
      if: ${{ failure() }}
      run: |
        cat .triplydb-js.err

  sync-triply:
    runs-on: ubuntu-latest
    needs: push-to-triply
    steps:
    - name: Sync changes to TriplyDB API via cURL
      run:  |
        curl -H 'Authorization: Bearer ${{ secrets.LDV_API_TOKEN }}' -H 'Content-Type: application/json' -X POST https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/${{ env.DATASET_NAME }}/services/kunstcollecties-harvest -d '{"sync": "true"}'
